name: Sync to Hugging Face Space

on:
  push:
    branches: [main]   # change if your repo's default branch is master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          SPACE_ID: LokeshIITM/iitm-project-02-data-analyst-agent
        run: |
          git lfs install
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add space https://LokeshIITM:${HF_TOKEN}@huggingface.co/spaces/${SPACE_ID}
          git push -f space HEAD:main
